#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S3,     irSensor,       sensorEV3_IRSensor)
#pragma config(Sensor, S4,     colorSensor,    sensorEV3_Color)
#pragma config(Motor,  motorA,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorC,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define   DATALOG_SERIES_0    0
#define   DATALOG_SERIES_1    1
#define   DATALOG_SERIES_2    2
#define   DATALOG_SERIES_3    3
#define   DATALOG_SERIES_4    4
#define   DATALOG_SERIES_5    5

//Creates variables to store the red, green, and blue values
long redValue;
long greenValue;
long blueValue;
long hueValue;
long distanceValue;

void kehrbesen()
{
	moveMotorTarget(armMotor, 520, 20);
	waitUntilMotorStop(armMotor);
	setMotorSpeed(armMotor, -10);
	while(getTouchValue(touchSensor) == 0) {
		delay(100);
	}
	playSound(soundLowBuzz);
	setMotorSpeed(armMotor, 0);
	setLEDColor(ledOrangeFlash);
	delay(1000);
}

task logcolors()
{
	while(true)
	{
		wait1Msec(10);
		getColorRGB(colorSensor,  redValue, greenValue, blueValue);
		hueValue = SensorValue[colorSensor];
		distanceValue = getIRDistance(irSensor);
		datalogDataGroupStart();
		datalogAddValue( DATALOG_SERIES_0, redValue );
		datalogAddValue( DATALOG_SERIES_1, greenValue );
		datalogAddValue( DATALOG_SERIES_2, blueValue );
		datalogAddValue( DATALOG_SERIES_3, distanceValue);
		datalogAddValue( DATALOG_SERIES_4, hueValue);
		datalogDataGroupEnd();
	}
	return;
}


task main()
{
	// Clear old data
	datalogClear();
	startTask(logcolors);

	moveMotorTarget(leftMotor, 2000, 10);
	moveMotorTarget(rightMotor, 2000, 10);
	waitUntilMotorStop(leftMotor);
	waitUntilMotorStop(rightMotor);

	kehrbesen();

	//moveMotorTarget(leftMotor, 580, 20);
	//moveMotorTarget(rightMotor, 580, -20);
	//waitUntilMotorStop(leftMotor);
	//waitUntilMotorStop(rightMotor);
	stopTask(logcolors);

}
